In [4]:
import pandas as pd
import numpy as np

df=pd.read_csv(r'C:\Users\X1 Carbon\OneDrive\Desktop\matches.csv')
print(df.shape)

(1095, 20)

In [5]:
print(df.dtypes)

id                   int64
season              object
city                object
date                object
match_type          object
player_of_match     object
venue               object
team1               object
team2               object
toss_winner         object
toss_decision       object
winner              object
result              object
result_margin      float64
target_runs        float64
target_overs       float64
super_over          object
method              object
umpire1             object
umpire2             object
dtype: object

In [7]:
print(df.isnull().sum())

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [8]:
df['date']=pd.to_datetime(df['date'],format='%Y-%m-%d')

In [10]:

print(df['date'].dtype)

datetime64[ns]

In [11]:
#new column
df['year']=df['date'].dt.year

In [12]:
# Remove single column

df = df.drop('season', axis=1)

In [13]:
df['city'] = df['city'].fillna('Unknown')

In [14]:
df['player_of_match'] = df['player_of_match'].fillna('No Award')

In [15]:
df['winner'] = df['winner'].fillna('No Result')

In [16]:
print(df['result_margin'].unique())
print(df['target_runs'].unique())
print(df['target_overs'].unique())

[140.  33.   9.   5.   6.   3.  66.   7.  10.   4.  13.  45.   8.  29.
  18.  23.  12.  65.  25.   1.  14.  41. 105.  19.  75.  92.  11.  24.
  nan  27.  38.  78.  16.  53.   2.  31.  55.  98.  34.  36.  17.  39.
  40.  67.  63.  37.  57.  35.  22.  21.  48.  26.  20.  85.  32.  76.
 111.  82.  43.  58.  28.  74.  42.  59.  46.  47.  86.  44.  87. 130.
  15.  60.  77.  30.  50.  93.  72.  62.  97. 138.  71. 144.  80.  51.
  61. 146.  64. 102. 118.  49.  69.  88.  54.  91.  52.  81.  56. 112.
 106.]
[223. 241. 130. 166. 111. 167. 143. 209. 215. 183. 136. 148. 155. 159.
 179. 138. 192. 165. 197. 170. 157. 163. 110. 127. 145. 104. 188. 141.
 182. 205. 144. 134. 195.  68.  89. 198.  53. 190. 176. 177. 212. 175.
 146. 123. 222. 193. 113. 164.  54. 102. 180.  69. 185. 151. 169. 150.
 140. 120. 149. 142. 154. 106. 187. 117. 158. 124. 174. 121. 161. 135.
 189. 171. 147. 162. 213. 191. 204. 219.  93. 186. 152. 172. 137. 156.
 184. 181. 178. 173. 247. 201. 160. 139. 112. 131. 133.  83.  96.  82.
 119. 196. 232.  95. 206.  52. 126.  98. 233. 153. 199.  nan 129. 194.
 116. 132. 125. 208. 101. 115. 216. 100. 210. 118. 264.  81. 224. 107.
  71.  43. 202. 227. 200. 128. 168. 236. 114. 203. 122.  99. 228.  61.
 249.  66. 207.  58. 214. 231.  74.  48. 108. 218. 220. 211. 246. 109.
  63. 217. 229.  85. 221.  91. 258. 234. 278. 273. 235. 288.  90. 267.
 225. 262. 242.]
[20.  16.   8.  18.   6.   9.2 17.  10.  13.   nan 12.   5.  11.   9.
 14.  15. ]

In [20]:
df[df['result_margin'].isna() | df['target_runs'].isna() | df['target_overs'].isna()][['date','team1','team2','result', 'winner', 'result_margin', 'target_runs', 'target_overs']]

,date,team1,team2,result,winner,result_margin,target_runs,target_overs
66,2009-04-23,Kolkata Knight Riders,Rajasthan Royals,tie,Rajasthan Royals,NaN,151.0,20.0
130,2010-03-21,Chennai Super Kings,Kings XI Punjab,tie,Kings XI Punjab,NaN,137.0,20.0
241,2011-05-21,Delhi Daredevils,Pune Warriors,no result,No Result,NaN,NaN,NaN
328,2013-04-07,Sunrisers Hyderabad,Royal Challengers Bangalore,tie,Sunrisers Hyderabad,NaN,131.0,20.0
342,2013-04-16,Royal Challengers Bangalore,Delhi Daredevils,tie,Royal Challengers Bangalore,NaN,153.0,20.0
416,2014-04-29,Kolkata Knight Riders,Rajasthan Royals,tie,Rajasthan Royals,NaN,153.0,20.0
475,2015-04-21,Rajasthan Royals,Kings XI Punjab,tie,Kings XI Punjab,NaN,192.0,20.0
485,2015-04-29,Royal Challengers Bangalore,Rajasthan Royals,no result,No Result,NaN,NaN,NaN
511,2015-05-17,Royal Challengers Bangalore,Delhi Daredevils,no result,No Result,NaN,188.0,20.0
610,2017-04-29,Gujarat Lions,Mumbai Indians,tie,Mumbai Indians,NaN,154.0,20.0
705,2019-03-30,Kolkata Knight Riders,Delhi Capitals,tie,Delhi Capitals,NaN,186.0,20.0
744,2019-04-30,Royal Challengers Bangalore,Rajasthan Royals,no result,No Result,NaN,63.0,5.0
746,2019-05-02,Mumbai Indians,Sunrisers Hyderabad,tie,Mumbai Indians,NaN,163.0,20.0
757,2020-09-20,Delhi Capitals,Kings XI Punjab,tie,Delhi Capitals,NaN,158.0,20.0
765,2020-09-28,Royal Challengers Bangalore,Mumbai Indians,tie,Royal Challengers Bangalore,NaN,202.0,20.0
790,2020-10-18,Kolkata Knight Riders,Sunrisers Hyderabad,tie,Kolkata Knight Riders,NaN,164.0,20.0
791,2020-10-18,Mumbai Indians,Kings XI Punjab,tie,Kings XI Punjab,NaN,177.0,20.0
835,2021-04-25,Delhi Capitals,Sunrisers Hyderabad,tie,Delhi Capitals,NaN,160.0,20.0
994,2023-05-03,Lucknow Super Giants,Chennai Super Kings,no result,No Result,NaN,NaN,NaN

In [24]:
df['result_margin'] = df['result_margin'].fillna(0)
df['target_runs']   = df['target_runs'].fillna(0)
df['target_overs']  = df['target_overs'].fillna(0)

# here i filled the NaN values of columns [result_margin, target_runs, target_overs] to 0 means 
# those matches might be cancelled or they are tie.

In [25]:
df[df['result_margin'].isna() | df['target_runs'].isna() | df['target_overs'].isna()]

Empty DataFrame
Columns: [id, city, date, match_type, player_of_match, venue, team1, team2, toss_winner, toss_decision, winner, result, result_margin, target_runs, target_overs, super_over, method, umpire1, umpire2, year]
Index: []

In [26]:
df['method'] = df['method'].replace('NA', np.nan)
df['method'] = df['method'].fillna('Normal')

In [27]:
print(df.isnull().sum())

id                 0
city               0
date               0
match_type         0
player_of_match    0
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
winner             0
result             0
result_margin      0
target_runs        0
target_overs       0
super_over         0
method             0
umpire1            0
umpire2            0
year               0
dtype: int64

In [31]:
print(df.dtypes)

id                          int64
city                       object
date               datetime64[ns]
match_type                 object
player_of_match            object
venue                      object
team1                      object
team2                      object
toss_winner                object
toss_decision              object
winner                     object
result                     object
result_margin             float64
target_runs               float64
target_overs              float64
super_over                 object
method                     object
umpire1                    object
umpire2                    object
year                        int32
dtype: object

In [33]:
print(df['match_type'].unique())

['League' 'Semi Final' 'Final' '3rd Place Play-Off' 'Qualifier 1'
 'Elimination Final' 'Qualifier 2' 'Eliminator']

In [39]:
df['result_margin'] = df['result_margin'].astype(int)
df['target_runs']   = df['target_runs'].astype(int)
df['target_overs']  = df['target_overs'].astype(int)

In [40]:
print(df.dtypes)

id                          int64
city                       object
date               datetime64[ns]
match_type                 object
player_of_match            object
venue                      object
team1                      object
team2                      object
toss_winner                object
toss_decision              object
winner                     object
result                     object
result_margin               int64
target_runs                 int64
target_overs                int64
super_over                 object
method                     object
umpire1                    object
umpire2                    object
year                        int32
dtype: object

In [41]:
df['super_over'] = df['super_over'].map({'Y': 1, 'N': 0})

In [44]:
#new column
df['toss_winner_won'] = (df['toss_winner'] == df['winner']).astype(int)

In [43]:
#re naming columns
df['home_team'] = df['team1']
df['away_team'] = df['team2']

In [45]:
# new columns
df['win_by_runs']    = (df['result'] == 'runs').astype(int)
df['win_by_wickets'] = (df['result'] == 'wickets').astype(int)

In [46]:
df.head()

,id,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,...,super_over,method,umpire1,umpire2,year,toss_winner_won,home_team,away_team,win_by_runs,win_by_wickets
0,335982,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,...,0,Normal,Asad Rauf,RE Koertzen,2008,0,Royal Challengers Bangalore,Kolkata Knight Riders,1,0
1,335983,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,...,0,Normal,MR Benson,SL Shastri,2008,1,Kings XI Punjab,Chennai Super Kings,1,0
2,335984,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,...,0,Normal,Aleem Dar,GA Pratapkumar,2008,0,Delhi Daredevils,Rajasthan Royals,0,1
3,335985,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,...,0,Normal,SJ Davis,DJ Harper,2008,0,Mumbai Indians,Royal Challengers Bangalore,0,1
4,335986,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,...,0,Normal,BF Bowden,K Hariharan,2008,0,Kolkata Knight Riders,Deccan Chargers,0,1

In [54]:
print(df.dtypes)

id                           int64
city                        object
date                datetime64[ns]
match_type                  object
player_of_match             object
venue                       object
team1                       object
team2                       object
toss_winner                 object
toss_decision               object
winner                      object
result                      object
result_margin                int64
target_runs                  int64
target_overs                 int64
super_over                   int64
method                      object
umpire1                     object
umpire2                     object
year                         int32
toss_winner_won              int64
home_team                   object
away_team                   object
win_by_runs                  int64
win_by_wickets               int64
home_team_result            object
dtype: object

In [47]:
def team1_result(row):
    if row['winner'] == row['home_team']:
        return 'Win'
    elif row['winner'] == 'No Result':
        return 'No Result'
    else:
        return 'Loss'
df['home_team_result'] = df.apply(team1_result, axis=1)

#new column

In [50]:
df['home_team'].unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals', 'Deccan Chargers', 'Chennai Super Kings',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Gujarat Lions', 'Rising Pune Supergiants',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

In [55]:
df = df.drop(columns=['team1', 'team2'])

In [56]:
team_rename = {
    'Delhi Daredevils'           : 'Delhi Capitals',
    'Kings XI Punjab'            : 'Punjab Kings',
    'Rising Pune Supergiant'     : 'Rising Pune Supergiants',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru',
    'Pune Warriors'              : 'Pune Warriors India',
}

cols=['toss_winner','winner','home_team','away_team']

for col in cols:
    df[col]=df[col].replace(team_rename)

In [58]:
df['toss_winner'].unique()

array(['Royal Challengers Bengaluru', 'Chennai Super Kings',
       'Rajasthan Royals', 'Mumbai Indians', 'Deccan Chargers',
       'Punjab Kings', 'Kolkata Knight Riders', 'Delhi Capitals',
       'Kochi Tuskers Kerala', 'Pune Warriors India',
       'Sunrisers Hyderabad', 'Gujarat Lions', 'Rising Pune Supergiants',
       'Gujarat Titans', 'Lucknow Super Giants'], dtype=object)

In [59]:
# Option A: CSV
df.to_csv('matches_clean.csv', index=False)
# Option B: Excel (recommended — preserves data types)
df.to_excel('matches_clean.xlsx', index=False, engine='openpyxl')

print('Export complete!')
print(f'Final shape: {df.shape}')
print(f'Columns: {list(df.columns)}')

Export complete!
Final shape: (1095, 24)
Columns: ['id', 'city', 'date', 'match_type', 'player_of_match', 'venue', 'toss_winner', 'toss_decision', 'winner', 'result', 'result_margin', 'target_runs', 'target_overs', 'super_over', 'method', 'umpire1', 'umpire2', 'year', 'toss_winner_won', 'home_team', 'away_team', 'win_by_runs', 'win_by_wickets', 'home_team_result']